
package com.nt.service;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Adhar", targetNamespace = "http://service.nt.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Adhar {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "insertRecord", targetNamespace = "http://service.nt.com/", className = "com.nt.service.InsertRecord")
    @ResponseWrapper(localName = "insertRecordResponse", targetNamespace = "http://service.nt.com/", className = "com.nt.service.InsertRecordResponse")
    @Action(input = "http://service.nt.com/Adhar/insertRecordRequest", output = "http://service.nt.com/Adhar/insertRecordResponse")
    public String insertRecord(
        @WebParam(name = "arg0", targetNamespace = "")
        UserDTO arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<com.nt.service.UserRDTO>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "fetchRecord", targetNamespace = "http://service.nt.com/", className = "com.nt.service.FetchRecord")
    @ResponseWrapper(localName = "fetchRecordResponse", targetNamespace = "http://service.nt.com/", className = "com.nt.service.FetchRecordResponse")
    @Action(input = "http://service.nt.com/Adhar/fetchRecordRequest", output = "http://service.nt.com/Adhar/fetchRecordResponse")
    public List<UserRDTO> fetchRecord(
        @WebParam(name = "arg0", targetNamespace = "")
        long arg0);

}
