
package com.nt.service;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "AdharMgmtServiceImplService", targetNamespace = "http://service.nt.com/", wsdlLocation = "http://localhost:3030/MVCProj22-MiniProject-WebServiceProvider-AdharApp/adhar?wsdl")
public class AdharMgmtServiceImplService
    extends Service
{

    private final static URL ADHARMGMTSERVICEIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException ADHARMGMTSERVICEIMPLSERVICE_EXCEPTION;
    private final static QName ADHARMGMTSERVICEIMPLSERVICE_QNAME = new QName("http://service.nt.com/", "AdharMgmtServiceImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:3030/MVCProj22-MiniProject-WebServiceProvider-AdharApp/adhar?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ADHARMGMTSERVICEIMPLSERVICE_WSDL_LOCATION = url;
        ADHARMGMTSERVICEIMPLSERVICE_EXCEPTION = e;
    }

    public AdharMgmtServiceImplService() {
        super(__getWsdlLocation(), ADHARMGMTSERVICEIMPLSERVICE_QNAME);
    }

    public AdharMgmtServiceImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), ADHARMGMTSERVICEIMPLSERVICE_QNAME, features);
    }

    public AdharMgmtServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, ADHARMGMTSERVICEIMPLSERVICE_QNAME);
    }

    public AdharMgmtServiceImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ADHARMGMTSERVICEIMPLSERVICE_QNAME, features);
    }

    public AdharMgmtServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public AdharMgmtServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns Adhar
     */
    @WebEndpoint(name = "AdharMgmtServiceImplPort")
    public Adhar getAdharMgmtServiceImplPort() {
        return super.getPort(new QName("http://service.nt.com/", "AdharMgmtServiceImplPort"), Adhar.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Adhar
     */
    @WebEndpoint(name = "AdharMgmtServiceImplPort")
    public Adhar getAdharMgmtServiceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://service.nt.com/", "AdharMgmtServiceImplPort"), Adhar.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ADHARMGMTSERVICEIMPLSERVICE_EXCEPTION!= null) {
            throw ADHARMGMTSERVICEIMPLSERVICE_EXCEPTION;
        }
        return ADHARMGMTSERVICEIMPLSERVICE_WSDL_LOCATION;
    }

}
